### ISSUE TITLE
Fail2ban doesn't start.

### ISSUE THREAD

**Issue by madmaddyz** [dd-dreams/aft#28]
ail2ban.service - Fail2Ban Service
     Loaded: loaded (/lib/systemd/system/fail2ban.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-11-16 14:16:59 CET; 35min ago
       Docs: man:fail2ban(1)
   Main PID: 62951 (code=exited, status=255/EXCEPTION)
        CPU: 61ms

Nov 16 14:16:59 NoJab systemd[1]: Started Fail2Ban Service.
Nov 16 14:16:59 NoJab fail2ban-server[62951]: 2023-11-16 14:16:59,141 fail2ban                [62951]: ERROR   Failed during configuration: Have not found any log file for nginx-http-auth jail
Nov 16 14:16:59 NoJab fail2ban-server[62951]: 2023-11-16 14:16:59,143 fail2ban                [62951]: ERROR   Async configuration of server failed
Nov 16 14:16:59 NoJab systemd[1]: fail2ban.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 16 14:16:59 NoJab systemd[1]: fail2ban.service: Failed with result 'exit-code'.
I'm also using logrotate. Could it be that fail2ban is unable to read information because a new file has been created?

**Comment by dd-dreams** [comment]
fail2ban is not yet supported (#23). It's a WIP.

**Comment by dd-dreams** [comment]
It has been added. Please check it.
